---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "8"

sudo: false
dist: trusty

addons:
  chrome: stable
  firefox: latest

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: tests
      name: "Linting"
      script: yarn lint:js
    - name: "TS type check"
      script: yarn lint:ts
    - name: "Basic tests"
      script: yarn test

    # runs tests against each supported Ember version
    - stage: ember version tests
      name: "Ember LTS 3.4"
      env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - name: "Ember LTS 3.8"
      env: EMBER_TRY_SCENARIO=ember-lts-3.8
    - name: "Ember LTS 3.12"
      env: EMBER_TRY_SCENARIO=ember-lts-3.12
    - name: "Ember Release"
      env: EMBER_TRY_SCENARIO=ember-release
    - name: "Ember Beta"
      env: EMBER_TRY_SCENARIO=ember-beta
    - name: "Ember Canary"
      env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/53eb4761db0a361a94a1
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
